### ISSUE TITLE
Add variation to demo page

### ISSUE THREAD

**Issue by munierujp** [standard/standard-www#40]
- standard (already exists)
- semistandard
  - Use [semistandard](https://github.com/standard/semistandard)
- TypeScript
  - Use [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript)

**Comment by feross** [comment]
I appreciate the suggestion here! I'd like to integrate `.ts` support directly into the main `standard` program. See: https://github.com/standard/standard/issues/1007 then we won't need to do anything special to get support for it on the website.

I don't think we want to include a demo for semistandard because the whole goal of `standard` is to have one style and offering options on our demo page may confuse new users.
